---
title: "Add any Plot to your {gt} table"
format: html
editor_options: 
  chunk_output_type: console
---

## [Add any Plot to your {gt} table](https://www.youtube.com/watch?v=qFOFMed18T4)

```{r}
library(tidyverse)
library(gt)
```


```{r}
penguins_weights <- palmerpenguins::penguins |> 
  summarize(
    min = min(body_mass_g, na.rm = TRUE), 
    mean = mean(body_mass_g, na.rm = TRUE), 
    max = max(body_mass_g, na.rm = TRUE), 
  .by = species
  )
```


```{r}
penguins_weights |> 
  gt() |> 
  tab_spanner(
    label = 'Penguin\'s weight', 
    columns = -species
  ) |> 
  cols_label_with(fn = str_to_title) |> 
  fmt_number(decimals = 2) |> 
  cols_align('left', columns = species)
```

```{r}
gentoo_data <- palmerpenguins::penguins |> 
  filter(species == "Gentoo")
```

```{r}
gentoo_data |> 
  ggplot() + 
  aes(x = body_mass_g, y = species) + 
  geom_violin(fill = "dodgerblue4") + 
  theme_void()
```


```{r}
plot_violin_species <- function(my_species) {
  
  gentoo_data <- palmerpenguins::penguins |> 
  filter(species == my_species)
  
  
  gentoo_data |> 
  ggplot() + 
  aes(x = body_mass_g, y = species) + 
  geom_violin(fill = "dodgerblue4") + 
  theme_void() +
  coord_cartesian(
    xlim = range(palmerpenguins::penguins$body_mass_g, na.rm = TRUE)
  )
  
}

```


```{r}
plot_violin_species(my_species = "Gentoo")
```

```{r}
penguins_weights |> 
  mutate(Distribution = species) |> 
  gt() |> 
  tab_spanner(
    label = 'Penguin\'s weight', 
    columns = -species
  ) |> 
  cols_label_with(fn = str_to_title) |> 
  fmt_number(decimals = 2) |> 
  cols_align('left', columns = species) |> 
  text_transform(
    locations = cells_body(columns = 'Distribution'), 
    fn = function(column){
      map(column, plot_violin_species) |> 
        ggplot_image(height = px(50), aspect_ratio = 3)
    }
  ) 
```

